Repository kubeclipper/console, pull requests merged in 2022-10, with the labels that each got.

#188 feat: add Version Info
  README.md
  src/asset/image/title.png
  src/components/Tools/index.jsx
  src/components/Tools/index.less
  src/components/VersionInfo/Version.jsx
  src/components/VersionInfo/index.jsx
  src/components/VersionInfo/index.less
  src/hooks/index.js
  src/hooks/useVersionInfo.js
  src/layouts/Base/Right/index.jsx
  src/pages/oauth/containers/Login/index.jsx
  src/pages/oauth/containers/Login/index.less
  src/stores/index.js
  src/stores/license.js
Labels: kind/feature, approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#189 perf: optimize import store
  src/stores/index.js
  src/stores/root.js
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#190 Revert "perf: optimize import store"
  src/stores/index.js
  src/stores/root.js
Labels: approved, lgtm, size/M, dco-signoff: no, do-not-merge/release-note-label-needed

#192 perf: optimize cluster operation tab
  src/components/Tables/Base/ActionButton/index.jsx
  src/components/Tables/Base/BatchAction/index.jsx
  src/components/Tables/Base/BatchAction/index.less
  src/components/Tables/Base/ItemAction/DropdownActions.jsx
  src/components/Tables/Base/ItemAction/index.less
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/Detail/NodesList/actions/Add.jsx
  src/pages/cluster/containers/Cluster/actions/RemoveNodes.jsx
  src/pages/cluster/containers/Cluster/actions/index.jsx
Labels: kind/feature, approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#195 feat: add nfs-csi support in cluster storage
  src/pages/cluster/components/plugin/uiSchemas.js
  src/utils/object.mapper.js
Labels: kind/feature, approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#196 feat: add kubeadm provider
  src/components/Tables/Base/ItemAction/DropdownActions.jsx
  src/containers/Tab/trendsTab.jsx
  src/containers/TabDetail/index.jsx
  src/pages/cluster/containers/Cluster/Detail/index.jsx
  src/pages/cluster/containers/Cluster/actions/Delete.jsx
  src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
  src/pages/cluster/containers/Cluster/actions/Upgrade.jsx
  src/pages/cluster/containers/Cluster/actions/index.jsx
  src/pages/cluster/containers/Hosting/Detail/Clusters/index.jsx
  src/pages/cluster/containers/Hosting/Detail/index.jsx
  src/pages/cluster/containers/Hosting/actions/Create.jsx
  src/pages/cluster/containers/Hosting/actions/Edit.jsx
  src/pages/cluster/containers/Hosting/actions/Remove.jsx
  src/pages/cluster/containers/Hosting/actions/Sync.jsx
  src/pages/cluster/containers/Hosting/actions/index.jsx
  src/pages/cluster/containers/Hosting/actions/index.less
  src/pages/cluster/containers/Hosting/index.jsx
  src/pages/cluster/routes/index.js
  src/stores/cloudprovider.js
  src/stores/root.js
  src/utils/form.templates.js
  src/utils/index.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/XL, dco-signoff: yes, do-not-merge/release-note-label-needed

#199 fix: fix revolve confilct err & i18n
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/index.jsx
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#201 fix: tip Incomplete display
  src/components/Tabs/index.less
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#203 fix: modify cluster name validate message
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#202 feat: add unit case
  jest.config.js
  src/utils/base64.js
  src/utils/base64.test.js
  src/utils/localStorage.test.js
  src/utils/validate.js
  src/utils/validate.test.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#205 feat: add deprecated tip in plugin
  src/components/Tabs/index.jsx
  src/components/Tabs/index.less
  src/locales/en.json
  src/locales/zh.json
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#210 feat: add fuzzy search for table
  src/components/Tables/Base/index.jsx
  src/containers/List/index.jsx
  src/pages/access/containers/Role/Detail/AuthorizedUsers/index.jsx
  src/pages/access/containers/Role/index.jsx
  src/pages/access/containers/User/index.jsx
  src/pages/cluster/containers/BackupPoint/index.jsx
  src/pages/cluster/containers/Cluster/Detail/Operation/index.jsx
  src/pages/cluster/containers/Cluster/index.jsx
  src/pages/cluster/containers/Hosting/Cluster/index.jsx
  src/pages/cluster/containers/Hosting/Detail/Clusters/index.jsx
  src/pages/cluster/containers/Hosting/index.jsx
  src/pages/cluster/containers/Template/cluster/index.jsx
  src/pages/cluster/containers/Template/plugin/index.jsx
  src/pages/region/containers/Region/Detail/ClusterList/index.jsx
  src/pages/region/containers/Region/index.jsx
  src/resources/backup.jsx
  src/utils/index.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#212 feat: add login in e2e test
  cypress.json
  cypress/config/config.yaml
  cypress/integration/pages/login.spec.js
  cypress/support/index.js
Labels: kind/feature, approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#213 perf: optimize cluster operation tab
  src/components/Tables/Base/ItemAction/index.less
  src/pages/cluster/containers/Cluster/actions/Delete.jsx
  src/pages/cluster/containers/Cluster/actions/Terminal.jsx
  src/pages/cluster/containers/Cluster/actions/index.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#214 fix: master node can not be selected
  src/pages/cluster/containers/Cluster/actions/RemoveNodes.jsx
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#216 fix: terminal port can not string
  src/pages/node/containers/Node/actions/Terminal.jsx
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#218 feat: upgrade cypress & add clster test
  .github/workflows/e2e-test.yml
  .yarnrc
  cypress.config.js
  cypress.json
  cypress/config/config.yaml
  cypress/e2e/pages/base/header.yc.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/error.cy.js
  cypress/e2e/pages/login.cy.js
  cypress/e2e/pages/node/node.cy.js
  cypress/e2e/pages/platform/license.cy.js
  cypress/e2e/pages/platform/platform.cy.js
  cypress/e2e/pages/region/region.cy.js
  cypress/e2e/pages/upgrade/plan.cy.js
  cypress/e2e/pages/upgrade/version.cy.js
  cypress/e2e/pages/user/role.cy.js
  cypress/e2e/pages/user/user.cy.js
  cypress/integration/pages/cluster/cluster.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/support/form-commands.js
  cypress/support/table-commands.js
  package.json
  src/components/Form/index.jsx
  src/components/StepForm/footer.jsx
  yarn.lock
Labels: approved, lgtm, size/XXL, dco-signoff: yes, do-not-merge/release-note-label-needed

#217 feat: add support https registry
  src/components/FormItem/IPGroup/index.jsx
  src/components/FormItem/index.jsx
  src/components/Tools/index.jsx
  src/core/menu.js
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Registry.jsx
  src/pages/cluster/containers/Cluster/actions/Upgrade.jsx
  src/pages/cluster/containers/Cluster/actions/index.jsx
  src/pages/cluster/containers/LocalRegistry/actions/Add.jsx
  src/pages/cluster/containers/Registry/actions/Add.jsx
  src/pages/cluster/containers/Registry/actions/Delete.jsx
  src/pages/cluster/containers/Registry/actions/index.jsx
  src/pages/cluster/containers/Registry/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/pages/cluster/routes/index.js
  src/stores/registry.js
  src/stores/root.js
  src/utils/form.templates.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/XL, dco-signoff: yes, do-not-merge/release-note-label-needed

#219 fix: modidy update registry msg
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Registry.jsx
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#220 fix: fix ip search in node table
  src/pages/node/containers/Node/index.jsx
  src/utils/object.mapper.js
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#221 fix: fix log search
  src/containers/List/index.jsx
  src/utils/index.js
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#222 fix: fix cluster registry cannot be empty
  src/pages/cluster/containers/Cluster/actions/Registry.jsx
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#223 feat: add e2e about backup
  cypress.config.js
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/support/commands.js
  cypress/support/form-commands.js
  cypress/support/table-commands.js
Labels: kind/feature, approved, lgtm, size/XL, dco-signoff: yes, do-not-merge/release-note-label-needed

#224 refactor: refactor ipgroup component
  src/components/FormItem/IPGroup/index.jsx
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed
