Repository kubeclipper/console, pull requests merged in 2022-12, with the labels that each got.

#306 fix: nodestore instance error
  src/pages/cluster/components/SelectNodes/index.jsx
  src/pages/cluster/containers/Cluster/Detail/NodesList/actions/Add.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#305 fix: adjust node test cases
  cypress.config.js
  cypress/e2e/pages/node/node.cy.js
Labels: size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#309 feat: add e2e case for kubeadm
  config/common.js
  cypress.config.js
  cypress/README.md
  cypress/config/config.yaml
  cypress/config/kubeconfig.yaml
  cypress/config/privateKey
  cypress/e2e/pages/access/oauth2.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/support/commands.js
  cypress/support/detail-command.js
  cypress/support/form-commands.js
  cypress/support/table-commands.js
  src/locales/en.json
  src/locales/zh.json
Labels: kind/feature, size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#304 feat: add testcase for region & registry
  .github/workflows/e2e-test.yml
  cypress.config.js
  cypress/config/config.yaml
  cypress/config/harborCa
  cypress/e2e/pages/access/platform-user-role.cy.js
  cypress/e2e/pages/base/header.cy.js
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/online-offline-install.cy.js
  cypress/e2e/pages/cluster/registry.cy.js
  cypress/e2e/pages/login.cy.js
  cypress/e2e/pages/platform/license.cy.js
  cypress/e2e/pages/platform/platform.cy.js
  cypress/e2e/pages/region/region.cy.js
  cypress/e2e/pages/test.cy.js
  cypress/e2e/pages/upgrade/plan.cy.js
  cypress/e2e/pages/upgrade/version.cy.js
  cypress/e2e/pages/user/role.cy.js
  cypress/e2e/pages/user/user.cy.js
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/support/detail-command.js
  cypress/support/form-commands.js
  cypress/support/resource.js
  cypress/support/table-commands.js
  src/pages/cluster/containers/Registry/index.jsx
Labels: approved, lgtm, size/XXL, dco-signoff: yes, do-not-merge/release-note-label-needed

#310 add testcase for plugin install
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/region/region.cy.js
  cypress/support/table-commands.js
Labels: size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#311 fix: modify e2e case for cluster
  cypress.config.js
  cypress/README.md
  cypress/config/config.yaml
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/e2e/pages/cluster/template.cy.js
  cypress/support/table-commands.js
Labels: size/L, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#312 feat: add case test log modal
  cypress/config/config.yaml
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/support/form-commands.js
Labels: approved, size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#314 fix: fix versionCross error
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#316 fix: e2e cases error
  cypress/config/config.yaml
  cypress/e2e/pages/access/oauth2.cy.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/support/commands.js
Labels: size/L, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#317 fix: modify locals for online offline registry
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
Labels: size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#319 fix: fix backup e2e case
  config/common.js
  cypress.config.js
  cypress/config/config.yaml
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/e2e/pages/cluster/online-offline-install.cy.js
  cypress/support/detail-command.js
  cypress/support/form-commands.js
  cypress/support/table-commands.js
  src/components/FormItem/index.jsx
  src/pages/cluster/containers/Cluster/actions/Edit.jsx
Labels: approved, size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#320 fix: e2e case error
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/template.cy.js
Labels: size/XS, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#322 fix: e2e case error
  cypress/e2e/pages/cluster/cluster.cy.js
Labels: size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#323 fix: e2e cases error
  config/common.js
  cypress/config/config.yaml
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/e2e/pages/cluster/online-offline-install.cy.js
  cypress/e2e/pages/cluster/registry.cy.js
  cypress/e2e/pages/cluster/template.cy.js
  cypress/e2e/pages/region/region.cy.js
  cypress/support/commands.js
Labels: size/L, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#325 fix: e2e case timeout
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/support/detail-command.js
  cypress/support/resource.js
  cypress/support/table-commands.js
  tools/test_cases_associated.js
Labels: approved, size/L, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#326 feat: add openstack rebuild
  .github/workflows/full-e2e-test.yml
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#327 fix: modify tip for delete backup space
  src/components/Tables/Base/ActionButton/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/BackupPoint/actions/Delete.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#328 fix: e2e summary resource
  tools/test_cases_associated.js
Labels: size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#329 fix: e2e summary resource
  tools/test_cases_associated.js
Labels: size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#330 fix: e2e config resource
  cypress/support/e2e.js
Labels: size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#332 fix: webpack dev support https
  config/webpack.dev.js
Labels: size/XS, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#333 fix: github e2e workflow add screenshots
  .github/workflows/full-e2e-test.yml
Labels: size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#335 fix: fix release action node version
  .github/workflows/release.yml
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed

#337 fix: project data is not updated timely
  src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/stores/base.js
  src/stores/templates.js
Labels: size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#338 fix: remove clearSearchInput in deletecluster(e2e)
  cypress/support/resource.js
Labels: size/XS, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#340 fix: modify e2e cases
  config/common.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/node/node.cy.js
  cypress/support/commands.js
Labels: size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#339 fix: remove assets and screenshots before scp
  .github/workflows/full-e2e-test.yml
Labels: size/XS, dco-signoff: yes, do-not-merge/release-note-label-needed

#341 fix: modify e2e cases
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/e2e/pages/cluster/template.cy.js
Labels: size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#343 fix: modify default value for create cluster
  src/resources/cluster.jsx
Labels: size/XS, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#348 fix: e2e cases error
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/support/commands.js
Labels: size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#349 fix: the params for create cluster
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
Labels: size/S, dco-signoff: yes, do-not-merge/release-note-label-needed

#352 fix: e2e cases error
  cypress/support/commands.js
  src/components/StepForm/footer.jsx
  src/pages/access/containers/Project/Detail/ProjectRole/Detail/AuthorityList/index.jsx
  src/pages/access/containers/Role/Detail/AuthorityList/index.jsx
Labels: size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#353 feat: add full e2e workflow on master
  .github/workflows/e2e-test.yml
  .github/workflows/full-e2e-test.yml
Labels: size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#354 fix: modify node version
  .github/workflows/buid.yaml
  .github/workflows/release.yml
  .github/workflows/unit-test.yml
Labels: size/XS, dco-signoff: yes, do-not-merge/release-note-label-needed

#355 feat: add cluster e2e cases
  cypress.config.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/support/commands.js
  cypress/support/resource.js
  src/containers/BaseDetail/index.jsx
Labels: size/XL, dco-signoff: yes, do-not-merge/release-note-label-needed

#356 feat: add CaCert for create cluster
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
  src/utils/object.mapper.js
Labels: kind/feature, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#357 fix: base64 CaCert for create cluster
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
Labels: size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#358 fix: delete backup space
  src/components/Tables/Base/ActionButton/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/BackupPoint/actions/Delete.jsx
Labels: size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#359 feat: stop during runtime
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/Detail/Operation/actions/Retry.jsx
  src/pages/cluster/containers/Cluster/Detail/Operation/actions/Stop.jsx
  src/pages/cluster/containers/Cluster/Detail/Operation/actions/index.jsx
  src/resources/cluster.jsx
  src/stores/operation.js
  src/utils/object.mapper.js
Labels: kind/feature, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#360 fix: adaptive v1.24 for create cluster
  src/pages/cluster/components/plugin/AddPlugin.jsx
  src/pages/cluster/components/plugin/AddStorage.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
Labels: size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#361 fix: the storageclass form used by select or input
  src/components/FormRender/index.jsx
  src/components/FormRender/widgets/SelectInput/index.jsx
  src/pages/cluster/components/plugin/uiSchemas.js
Labels: approved, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed
