Repository kubeclipper/console, pull requests merged in 2022-09, with the labels that each got.

#143 fix: hidden jwtSecret when clusterRole is member
  src/pages/cluster/components/plugin/uiSchemas.js
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#141 feat filter cluster k8s version architecture according to nodes
  src/components/FormItem/SelectForValue/index.jsx
  src/components/FormItem/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/components/SelectNodes/List.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
  src/stores/cluster.js
  src/utils/index.js
  src/utils/object.mapper.js
Labels: kind/feature, approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#145 feat add backup rootdir tip
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/BackupPoint/actions/Create.jsx
Labels: kind/feature, approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#146 fix oauth2 redirect & aouth2 login failed
  src/stores/index.js
  src/utils/index.js
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#152 fix sort k8s version
  src/stores/cluster.js
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#153 fix login button loading
  src/hooks/useModal.js
  src/pages/oauth/containers/Login/index.jsx
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#155 fix modify cluaster IPv4 Autodetection Tip
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/resources/cluster.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#159 fix: fix i18n
  src/locales/en.json
  src/locales/zh.json
  src/pages/oauth/containers/Login/Verification.jsx
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#161 feat add auto open first log and show latest in operation log
  src/pages/cluster/containers/Cluster/Detail/Operation/actions/PipelineLogDialog/LeftSteps.jsx
  src/pages/cluster/containers/Cluster/Detail/Operation/actions/PipelineLogDialog/RightLogContent.jsx
  src/pages/cluster/containers/Cluster/Detail/Operation/actions/PipelineLogDialog/index.jsx
  src/pages/cluster/containers/Cluster/Detail/Operation/actions/PipelineLogDialog/index.less
  src/stores/log.js
  src/stores/operation.js
Labels: kind/feature, approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#164 fix: the list of footer select limit can not be selected
  src/containers/List/index.jsx
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#167 feat: add expiration tag in cluster list
  src/components/Tables/Base/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/resources/cluster.jsx
Labels: kind/feature, approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#169 fix: restrict removal of storage classes
  src/containers/Action/ConfirmAction/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/Detail/Storage/actions/RemovePlugin.jsx
  src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#170 feat: add base64js and modify some utils、components
  src/components/Icon/index.jsx
  src/components/Status/index.jsx
  src/components/StatusReason/index.jsx
  src/components/StatusReason/index.less
  src/components/Tips/index.jsx
  src/components/Tips/index.less
  src/locales/basezh.json
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Backup.jsx
  src/pages/cluster/containers/Cluster/actions/Delete.jsx
  src/pages/cluster/containers/Cluster/actions/Edit.jsx
  src/pages/cluster/containers/Cluster/actions/KubeConfig.jsx
  src/pages/cluster/containers/Cluster/actions/LinkAddPlugin.jsx
  src/pages/cluster/containers/Cluster/actions/LinkAddStorage.jsx
  src/pages/cluster/containers/Cluster/actions/Reset.jsx
  src/pages/cluster/containers/Cluster/actions/Restore.jsx
  src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
  src/pages/cluster/containers/Cluster/actions/ScheduledBackup.jsx
  src/pages/cluster/containers/Cluster/actions/Terminal.jsx
  src/pages/cluster/containers/Cluster/actions/UpdateLicense.jsx
  src/pages/cluster/containers/Cluster/actions/Upgrade.jsx
  src/utils/base64.js
  src/utils/index.js
  src/utils/object.mapper.js
  src/utils/validate.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#174 fix: details page tabs customization
  src/containers/Tab/trendsTab.jsx
  src/pages/cluster/containers/Cluster/Detail/index.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#176 feat: add cluster status locals(remove)
  src/locales/en.json
  src/locales/zh.json
  src/resources/cluster.jsx
Labels: kind/feature, approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#180 fix: browser compatibility issues about function findlastindex with operation log loading
  src/pages/cluster/containers/Cluster/Detail/Operation/actions/PipelineLogDialog/index.jsx
Labels: approved, lgtm

#182 fix: add validator in kubelet data dir
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#184 fix: the interface does not prompt information when deleting a cluster with backup
  src/components/Tables/Base/ActionButton/index.jsx
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#185 fix: rewrite default git version command
  config/webpack.prod.js
Labels: approved, size/XS, lgtm, kind/bug, release-note-none, dco-signoff: yes
