Repository kubeclipper/console, pull requests merged in 2022-11, with the labels that each got.

#225 fix: node list error in cluster detail
  src/pages/cluster/containers/Cluster/Detail/NodesList/actions/Add.jsx
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#226 fix: modify reg for path(add '-')
  src/utils/regex.js
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#227 fix: add plugin can not be confirm
  cypress.config.js
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/detail.cy.js
  cypress/support/form-commands.js
  src/pages/cluster/components/plugin/AddPlugin.jsx
Labels: approved, size/L, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#228 fix: modify cluster detail with controlPlaneHealth
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
  src/utils/object.mapper.js
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#229 fix: scheduled backup can not be sort by create time
  src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/index.jsx
Labels: approved, lgtm

#230 fix: modify locals
  src/locales/zh.json
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#231 fix: modify locals (backup point -> backup space)
  src/core/menu.js
  src/locales/basezh.json
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/BackupPoint/actions/Create.jsx
  src/pages/cluster/containers/BackupPoint/actions/Delete.jsx
  src/pages/cluster/containers/BackupPoint/actions/Edit.jsx
  src/pages/cluster/containers/BackupPoint/index.jsx
  src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
  src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Add.jsx
  src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Edit.jsx
  src/pages/cluster/containers/Cluster/actions/Backup.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Edit.jsx
  src/pages/cluster/containers/Cluster/actions/ScheduledBackup.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/resources/backup.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#232 fix: modify struct for backup space description
  src/pages/cluster/containers/BackupPoint/actions/Create.jsx
  src/pages/cluster/containers/BackupPoint/actions/Edit.jsx
  src/utils/object.mapper.js
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#233 fix: modify styles for status reason
  src/components/StatusReason/index.less
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#235 feat: add e2e about upgrade cluster
  cypress.config.js
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/detail.cy.js
  cypress/e2e/pages/cluster/upgrade.cy.js
  cypress/support/commands.js
Labels: kind/feature, approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#236 fix: detail info cannot be catched
  src/containers/BaseDetail/index.jsx
  src/containers/Tab/trendsTab.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#237 fix: delete trendstabs case
  src/containers/Tab/TrendsTab.jsx
  src/containers/Tab/trendsTab.jsx
Labels: approved, size/L, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#238 fix: add trendstab file
  src/containers/Tab/TrendsTab.jsx
Labels: approved, size/L, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#239 perf: warning: can't perform a React state update on an unmounted com…
  src/components/Tables/Base/ItemAction/index.jsx
  src/layouts/Base/Right/index.jsx
  src/layouts/Base/index.jsx
  src/utils/schemaForm.js
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#240 fix: use plugin template error & operaiton list cached by cluster detail
  src/pages/cluster/components/plugin/AddPlugin.jsx
  src/pages/cluster/components/plugin/PluginForm.jsx
  src/pages/cluster/containers/Cluster/Detail/Operation/index.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#242 fix: fix template data init failed
  src/pages/cluster/containers/Cluster/actions/Registry.jsx
  src/pages/cluster/containers/Template/plugin/actions/Create.jsx
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#243 fix: fix template tab default active not set
  src/containers/Tab/index.jsx
  src/pages/cluster/containers/Template/index.jsx
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#246 fix: fix containerruntime display in cluster detail
  src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#248 fix: plugin cannot be removed when cluster is no running
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
  src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#249 fix: plugin cannot be removed when cluster is no running
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
  src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#251 fix: fix template active tab err
  src/pages/cluster/containers/Template/index.jsx
  src/pages/cluster/containers/Template/plugin/actions/Create.jsx
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#253 fix: edit pugin data without backfill
  src/components/FormRender/widgets/KSPlugins/index.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#257 fix: fix Registries null triger js error
  config/webpack.prod.js
  src/components/ErrorBoundary/index.jsx
  src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#259 fix: use template can not be edited
  src/components/FormRender/widgets/KSPlugins/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/components/plugin/PluginForm.jsx
  src/pages/cluster/components/plugin/RenderForm.jsx
  src/pages/cluster/components/plugin/StorageForm.jsx
  src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#260 fix: use template can not be edited
  src/components/FormRender/widgets/KSPlugins/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/components/plugin/PluginForm.jsx
  src/pages/cluster/components/plugin/RenderForm.jsx
  src/pages/cluster/components/plugin/StorageForm.jsx
  src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#261 fix: remove errorbounadry outside router
  src/core/App.jsx
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#264 fix: add scheduled backup tip error in cluster dashboard
  src/pages/cluster/containers/Cluster/actions/ScheduledBackup.jsx
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#266 feat: add node assign project
  config/common.js
  src/containers/Action/ModalAction/index.jsx
  src/containers/Action/StepAction/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/node/containers/Node/actions/AssignProject.jsx
  src/pages/node/containers/Node/actions/index.jsx
  src/stores/base.js
  src/stores/index.js
  src/stores/node.js
  src/stores/templates.js
  src/utils/object.mapper.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#267 fix: rancher healthy not displayed
  src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#268 fix: fix template api path
  src/stores/templates.js
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#270 feat: cluster hosting add project
  src/containers/List/index.jsx
  src/pages/cluster/containers/Cluster/index.jsx
  src/pages/cluster/containers/Hosting/actions/Create.jsx
  src/pages/cluster/containers/Hosting/index.jsx
  src/pages/node/containers/Node/index.jsx
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#271 fix: calico saved failed in cluster template
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#273 fix: storage used failed & modify cinder base64
  src/pages/cluster/components/plugin/AddPlugin.jsx
  src/pages/cluster/components/plugin/AddStorage.jsx
  src/pages/cluster/components/plugin/StorageForm.jsx
  src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#275 feat: modify dockerfile
  .dockerignore
  Dockerfile
  docker/Caddyfile
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#277 feat: add workflow
  .github/workflows/build-image.yml
  Dockerfile
Labels: approved, lgtm, size/M, release-note-none, dco-signoff: yes

#278 fix: adapt to the e2e environment
  config/common.js
  config/webpack.dev.js
  package.json
  src/components/Terminal/index.jsx
  src/stores/websocket.js
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#281 ci: add e2e check in workflow
  .github/workflows/front-e2e-test.yml
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#282 ci: adjust e2e workflow
  .github/workflows/build-image.yml
  .github/workflows/e2e-test.yml
  .github/workflows/front-e2e-test.yml
  .gitignore
  config/webpack.e2e.js
  cypress.config.js
  cypress/config/config.yaml
  cypress/e2e/pages/login.cy.js
  cypress/utils/index.js
  src/stores/index.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#286 ci: adjust e2e workflow
  .github/workflows/build-image.yaml
  .github/workflows/e2e-test.yml
  .gitignore
  config/webpack.e2e.js
  cypress.config.js
  cypress/config/config.yaml
Labels: approved, size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#288 fix: adjust e2e case
  config/common.js
  cypress.config.js
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/detail.cy.js
  cypress/e2e/pages/cluster/upgrade.cy.js
  cypress/support/common.js
  cypress/support/context.js
  cypress/support/e2e.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#292 Revert "fix: adjust e2e case"
  config/common.js
  cypress.config.js
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/detail.cy.js
  cypress/e2e/pages/cluster/upgrade.cy.js
  cypress/support/common.js
  cypress/support/context.js
  cypress/support/e2e.js
Labels: approved, size/L, dco-signoff: no, do-not-merge/release-note-label-needed

#291 fix: fix e2e case
  .github/workflows/e2e-test.yml
  config/common.js
  cypress.config.js
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/detail.cy.js
  cypress/e2e/pages/cluster/upgrade.cy.js
  cypress/support/commands.js
  cypress/support/form-commands.js
  src/containers/BaseDetail/index.jsx
Labels: approved, size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#293 fix: fix e2e command
  cypress.config.js
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/online-offline-install.cy.js
  cypress/e2e/pages/cluster/platform-user&role.cy.js
  cypress/support/commands.js
  cypress/support/form-commands.js
  cypress/support/resource-command.js
  cypress/support/table-commands.js
  src/components/StepForm/footer.jsx
  src/components/Tabs/index.jsx
Labels: approved, size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#297 fix: fix remove import
  cypress/support/e2e.js
Labels: approved, size/XS, dco-signoff: yes, do-not-merge/release-note-label-needed

#298 feat: add access test case
  cypress.config.js
  cypress/e2e/pages/access/platform-user&role.cy.js
  cypress/e2e/pages/cluster/online-offline-install.cy.js
  cypress/e2e/pages/test.cy.js
  cypress/support/table-commands.js
Labels: approved, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#299 docs: add Cypress Command Introduction
  cypress/README.md
  cypress/support/commands.js
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#300 feat: add e2e case about oauth2
  cypress.config.js
  cypress/README.md
  cypress/e2e/pages/access/oauth2.cy.js
  cypress/support/commands.js
  src/pages/oauth/containers/Login/oauth.jsx
  tools/test_cases_associated.js
Labels: kind/feature, size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#301 feat: add access e2e cases
  cypress.config.js
  cypress/README.md
  cypress/e2e/pages/access/platform-user-role.cy.js
  cypress/support/e2e.js
  cypress/support/form-commands.js
  cypress/support/resource.js
  cypress/support/table-commands.js
  cypress/utils/index.js
  src/components/Tables/Base/ItemAction/DropdownActions.jsx
  src/components/Tabs/index.jsx
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#303 feat: add access test cases
  cypress/e2e/pages/access/platform-user-role.cy.js
  cypress/support/detail-command.js
  cypress/support/e2e.js
  cypress/support/form-commands.js
  cypress/support/resource.js
  cypress/support/table-commands.js
  src/containers/TabDetail/index.jsx
Labels: approved, size/L, dco-signoff: yes, do-not-merge/release-note-label-needed
