Repository kubeclipper/console, pull requests merged in 2022-07, with the labels that each got.

#5 feat: add workflows.
  .github/workflows/buid.yaml
  .github/workflows/e2e-test.yml
  .github/workflows/release.yml
  .github/workflows/unit-test.yml
Labels: approved, size/L, kind/flake, lgtm, release-note-none, dco-signoff: yes

#4 fix: some bugs
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/components/PluginForm/index.jsx
  src/pages/cluster/components/PluginForm/storageFrom.jsx
  src/pages/cluster/containers/Cluster/actions/AddPlugin.jsx
  src/pages/cluster/containers/Cluster/actions/AddStorage.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Template/plugin/actions/Create.jsx
  src/stores/cluster.js
  src/stores/templates.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/XL, release-note-none, dco-signoff: yes

#9 fix: fix unit test failure
  .husky/commit-msg
  config/common.js
  src/resources/node.test.js
  src/utils/cookie.test.js
  src/utils/policy.test.js
  src/utils/validate.test.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#7 fix cluster template deletion error
  src/components/Form/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Delete.jsx
  src/pages/cluster/containers/Template/plugin/actions/Create.jsx
  src/styles/base.less
  src/utils/object.mapper.js
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#11 Add workflow action
  .github/workflows/commitlint.yml
  docs/test.md
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#13 fix cluster detail storage crad can be save as template
  src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
  src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx
  src/pages/cluster/containers/Cluster/Detail/index.jsx
  src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
Labels: approved, lgtm, size/M, kind/bug, release-note-none, dco-signoff: yes

#16 fix creating the cluster template, the version is empty
  src/utils/object.mapper.js
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#18 fix: fix plugin step is empty when without plugin component when create cluster
  src/components/StepForm/index.jsx
  src/components/StepForm/steps.jsx
  src/pages/cluster/components/PluginForm/index.jsx
  src/pages/cluster/components/PluginForm/storageFrom.jsx
  src/pages/cluster/components/Tips/index.jsx
  src/pages/cluster/containers/Cluster/actions/AddPlugin.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Storage.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Storage.jsx
  src/pages/cluster/containers/Template/plugin/actions/Create.jsx
  src/stores/cluster.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#20 fix: fix storageFrom.jsx rename failure [skip actions]
  src/components/FormRender/widgets/KSPlugins/index.jsx
  src/pages/cluster/components/plugin/Context.jsx
  src/pages/cluster/components/plugin/PluginForm.jsx
  src/pages/cluster/components/plugin/RenderForm.jsx
  src/pages/cluster/components/plugin/StorageForm.jsx
  src/pages/cluster/components/plugin/index.less
  src/pages/cluster/components/plugin/uiSchemas.js
  src/pages/cluster/containers/Cluster/actions/AddPlugin.jsx
  src/pages/cluster/containers/Cluster/actions/AddStorage.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Plugin.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Storage.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Plugin.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Storage.jsx
  src/pages/cluster/containers/Template/plugin/actions/Create.jsx
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#22 fix: fix @ resolve path result in build err
  .eslintrc
  config/webpack.common.js
  jest.config.js
  jsconfig.json
  src/components/FormRender/widgets/KSPlugins/index.jsx
  src/pages/cluster/containers/Cluster/actions/AddPlugin.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Plugin.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Plugin.jsx
  src/pages/cluster/containers/Template/plugin/actions/Create.jsx
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#24 fix: plugin template deletion error
  src/pages/cluster/containers/Template/plugin/actions/Delete.jsx
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#26 fix: fix plugin render loop
  src/pages/cluster/components/plugin/PluginForm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#30 fix: fix err when click prev in last create cluster step
  cypress/config/config.yaml
  src/components/StepForm/index.jsx
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#28 fix file circular reference
  src/stores/base.js
  src/stores/cluster.js
Labels: approved, size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#32 fix: fix websocket url err
  src/stores/websocket.js
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#34 fix cluster structure change
  src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/utils/object.mapper.js
Labels: approved, size/L, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#36 fix: fix cluster status
  src/pages/cluster/containers/Cluster/actions/index.jsx
  src/resources/cluster.jsx
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed
