Repository kubeclipper/console, pull requests merged in 2022-08, with the labels that each got.

#38 fix the cluster log cannot be closed
  src/stores/log.js
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#40 fix locals 'Deleting' to 'Terminating'
  src/components/Status/index.jsx
  src/locales/basezh.json
  src/pages/cluster/containers/Cluster/Detail/Operation/actions/ViewLog.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#42 fix plugin cannot be installed
  src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
  src/stores/cluster.js
  src/utils/object.mapper.js
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#46 fix: fix upgrade cluster check
  src/pages/cluster/containers/Cluster/actions/Upgrade.jsx
  src/utils/index.js
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#48 fix modify template structure
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
  src/resources/cluster.jsx
  src/resources/common.js
  src/stores/cluster.js
  src/utils/object.mapper.js
Labels: approved, size/L, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#50 feat add kubectl datadir in create cluster
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
  src/resources/cluster.jsx
  src/utils/object.mapper.js
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#52 fix createQuickly in create cluster
  src/components/StepForm/footer.jsx
  src/components/StepForm/index.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#54 fix offline environment access online api page white screen
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/stores/cluster.js
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#56 fix backup does not display the k8s version and edit backup
  src/pages/cluster/containers/Cluster/Detail/Backup/actions/Edit.jsx
  src/pages/cluster/containers/Cluster/actions/Backup.jsx
  src/utils/object.mapper.js
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#58 fix the plugin data is not cached after the next step during create cluster
  src/pages/cluster/components/plugin/PluginForm.jsx
  src/utils/object.mapper.js
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#61 the platform configuration button moves to cluster management
  src/core/menu.js
  src/core/routes.js
  src/pages/cluster/containers/PlatformConfig/actions/Add.jsx
  src/pages/cluster/containers/PlatformConfig/actions/Delete.jsx
  src/pages/cluster/containers/PlatformConfig/actions/index.jsx
  src/pages/cluster/containers/PlatformConfig/commonRegistry.jsx
  src/pages/cluster/containers/PlatformConfig/index.jsx
  src/pages/cluster/routes/index.js
  src/pages/configuration/App.jsx
  src/pages/configuration/routes/index.js
Labels: kind/feature, approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#67 After selecting the plugin template, the storage error has been opened
  src/pages/cluster/components/plugin/StorageForm.jsx
  src/pages/cluster/containers/Cluster/actions/AddStorage.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#69 fix: fix cluster detail basic info not display master ip
  src/stores/base.js
  src/stores/cluster.js
  src/utils/object.mapper.js
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#70 fix: fix base.js
  src/stores/base.js
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#71 fix error saving parameters as template
  src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
  src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx
  src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Template/plugin/actions/Create.jsx
  src/utils/object.mapper.js
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#75 fix: fix schedulebackup notify err
  src/containers/Action/ModalAction/index.jsx
  src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Add.jsx
Labels: approved, size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#74 fix the online locaregistry in the cluster details only displays 'online'
  src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#78 fix: change the platform configuration to registry, and remove the tabs
  src/core/menu.js
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/LocalRegistry/actions/Add.jsx
  src/pages/cluster/containers/LocalRegistry/actions/Delete.jsx
  src/pages/cluster/containers/LocalRegistry/actions/index.jsx
  src/pages/cluster/containers/LocalRegistry/index.jsx
  src/pages/cluster/containers/PlatformConfig/index.jsx
  src/pages/cluster/routes/index.js
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#82 fix: add HostClusterName select options
  src/components/FormRender/index.less
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/components/plugin/PluginForm.jsx
  src/pages/cluster/components/plugin/index.less
  src/pages/cluster/components/plugin/uiSchemas.js
  src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#80 fix edit cluster template notification error
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
Labels: approved, size/XS, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#84 fix select month end error for scheduled backup
  src/components/Form/index.jsx
  src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Add.jsx
  src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Edit.jsx
  src/pages/cluster/containers/Cluster/actions/ScheduledBackup.jsx
  src/resources/backup.jsx
Labels: approved, size/L, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#87 fix: fix notify err when remove storage
  src/containers/Action/ConfirmAction/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/LinkAddPlugin.jsx
  src/pages/cluster/containers/Cluster/actions/LinkAddStorage.jsx
  src/pages/cluster/containers/Cluster/actions/RemovePlugin.jsx
  src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
  src/pages/cluster/containers/Cluster/actions/ScheduledBackup.jsx
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#88 fix: refresh token does not match expires
  src/stores/index.js
  src/utils/request.js
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#91 fix: update ci,upload to oss when add a tag.
  .github/workflows/release.yml
Labels: approved, size/S, kind/flake, lgtm, release-note-none, dco-signoff: yes

#92 fix: fix role
  src/core/menu.js
  src/locales/basezh.json
  src/pages/cluster/containers/BackupPoint/actions/Create.jsx
  src/pages/cluster/containers/BackupPoint/actions/Delete.jsx
  src/pages/cluster/containers/BackupPoint/actions/Edit.jsx
  src/pages/cluster/containers/Cluster/actions/LinkAddPlugin.jsx
  src/pages/cluster/containers/Cluster/actions/LinkAddStorage.jsx
  src/pages/cluster/containers/Cluster/actions/Terminal.jsx
  src/pages/cluster/containers/LocalRegistry/actions/Add.jsx
  src/pages/cluster/containers/LocalRegistry/actions/Delete.jsx
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#94 fix: ahead of 10 minutes refresh token
  src/utils/request.js
Labels: approved, size/XS, lgtm, kind/bug, release-note-none, dco-signoff: yes

#95 fix: fix template offline field error
  src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
  src/utils/object.mapper.js
Labels: approved, lgtm, size/M, release-note-none, dco-signoff: yes

#98 enable upload test coverage in push evnet
  .github/workflows/e2e-test.yml
  .github/workflows/unit-test.yml
Labels: approved, size/S, kind/flake, lgtm, release-note-none, dco-signoff: yes

#100 fix: remove addplugin action when components no pligun
  src/components/Tables/Base/ItemAction/index.jsx
  src/layouts/Base/index.jsx
  src/pages/cluster/containers/Cluster/actions/LinkAddPlugin.jsx
  src/stores/cluster.js
  src/stores/index.js
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#104 refactor remove cluster components and use global components
  src/pages/cluster/components/plugin/PluginForm.jsx
  src/pages/cluster/components/plugin/StorageForm.jsx
  src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
  src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx
  src/pages/cluster/containers/Cluster/Detail/index.jsx
  src/pages/cluster/containers/Cluster/actions/AddPlugin.jsx
  src/pages/cluster/containers/Cluster/actions/AddStorage.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Plugin.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Plugin.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Storage.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Template/index.jsx
  src/pages/cluster/containers/Template/plugin/actions/Create.jsx
  src/stores/cluster.js
  src/stores/index.js
Labels: approved, size/L, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#108 fix the image type can not be saved when saving cluster as a template
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
  src/utils/object.mapper.js
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#111 fix: scheduled backup weekly dictionary error
  src/components/FormItem/SelectCycle/index.jsx
  src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Edit.jsx
  src/resources/date.jsx
  src/utils/index.js
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#114 feat: cluster backup add batch delete
  src/pages/cluster/containers/Cluster/Detail/Backup/actions/index.jsx
Labels: kind/feature, approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#117 fix: error in the last step of cluster quick creation
  src/components/StepForm/footer.jsx
  src/components/StepForm/index.jsx
  src/pages/cluster/components/plugin/PluginForm.jsx
  src/pages/cluster/components/plugin/StorageForm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Storage.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Storage.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
Labels: approved, size/L, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#118 docs: add docs
  Dockerfile
  README.md
  docker/prod.dockerfile
  docs/1-ready-to-work.md
  docs/2-catalog-introduction.md
  docs/3-I18n-introduction.md
  docs/4-test.md
  package.json
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#124 fix: fix token expire not redirect to login
  src/stores/index.js
  src/utils/request.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#123 fix sort by createtime is not work
  src/components/Tables/Base/index.jsx
  src/containers/List/index.jsx
Labels: approved, lgtm, size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#128 fix region default value
  src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
Labels: approved, size/S, lgtm, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#130 feat: add ErrorBoundary
  src/components/ErrorBoundary/index.jsx
  src/core/App.jsx
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#131 feat: add login verification
  src/hooks/index.js
  src/hooks/useModal.js
  src/locales/en.json
  src/locales/zh.json
  src/pages/oauth/containers/Login/Verification.jsx
  src/pages/oauth/containers/Login/index.jsx
  src/pages/oauth/containers/Login/index.less
  src/stores/index.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#134 feat modify data structure of componentmeta interface
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Cluster/actions/Upgrade.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
  src/resources/cluster.jsx
  src/stores/cluster.js
  src/utils/index.js
  src/utils/object.mapper.js
Labels: kind/feature, approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#135 feat: add ErrorBoundary
  src/components/ErrorBoundary/index.jsx
  src/components/NotFound/index.jsx
  src/components/NotFound/index.less
  src/components/Tables/Base/ActionButton/ActionModal.jsx
  src/layouts/Base/Right/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/styles/base.less
Labels: approved, lgtm, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#136 fix: fix request.js
  src/utils/request.js
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed
