Repository kubeclipper/console, pull requests merged in 2023-01, with the labels that each got.

#362 fix: adaptive v1.24 for create cluster
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
Labels: size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#364 feat: add metalb plugin
  src/pages/cluster/components/plugin/AddPlugin.jsx
  src/pages/cluster/components/plugin/PluginForm.jsx
  src/pages/cluster/components/plugin/uiSchemas.js
  src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
  src/utils/object.mapper.js
Labels: kind/feature, size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#365 fix: format time for scheduledBackup
  src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Edit.jsx
Labels: size/XS, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#366 cp CRI registry to 2022-9-9
  config/webpack.dev.js
  src/components/FormItem/IPGroup/index.jsx
  src/components/FormItem/index.jsx
  src/components/Tools/index.jsx
  src/core/menu.js
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Registry.jsx
  src/pages/cluster/containers/Cluster/actions/Upgrade.jsx
  src/pages/cluster/containers/Cluster/actions/index.jsx
  src/pages/cluster/containers/LocalRegistry/actions/Add.jsx
  src/pages/cluster/containers/Registry/actions/Add.jsx
  src/pages/cluster/containers/Registry/actions/Delete.jsx
  src/pages/cluster/containers/Registry/actions/index.jsx
  src/pages/cluster/containers/Registry/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/pages/cluster/routes/index.js
  src/stores/registry.js
  src/stores/root.js
  src/utils/form.templates.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/XL, dco-signoff: yes, do-not-merge/release-note-label-needed

#367 feat: add cluster node name for create cluster
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
Labels: kind/feature, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#368 feat: add cluster node name for create cluster
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
Labels: size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#369 fix: start error
  src/stores/root.js
  src/stores/template.js
Labels: size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed
