Repository kubeclipper/console, pull requests merged in 2023-09, with the labels that each got.

#405 fix: add kube dist on kc-console
  .github/workflows/buid.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#406 fix: github actions
  .github/workflows/buid.yaml
  .github/workflows/build-image.yml
Labels: approved, lgtm, size/M, kind/bug, release-note-none, dco-signoff: yes

#407 fix: modify build aciton
  .github/workflows/buid.yaml
  config/webpack.dev.js
Labels: size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#409 fix: add kube-console on release kc-console
  .github/workflows/release.yml
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed
