Repository kubeclipper/console, pull requests merged in 2023-02, with the labels that each got.

#370 feat: add audit module
  src/core/menu.js
  src/core/routes.js
  src/pages/audit/App.jsx
  src/pages/audit/containers/LoginLog/index.jsx
  src/pages/audit/containers/OperationLog/index.jsx
  src/pages/audit/routes/index.js
  src/resources/audit.js
  src/stores/audit.js
  src/stores/root.js
Labels: approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#371 perf: adjust commitref access method
  .babelrc
  .env
  build.sh
  config/webpack.common.js
  config/webpack.dev.js
  config/webpack.e2e.js
  config/webpack.prod.js
  package.json
  src/components/VersionInfo/Version.jsx
  src/core/App.jsx
  src/core/index.js
  src/locales/en.json
  src/locales/zh.json
  yarn.lock
Labels: approved, lgtm, size/XXL, dco-signoff: yes, do-not-merge/release-note-label-needed

#372 feat: add cypress test
  cypress.config.js
  cypress/e2e/pages/access/oauth2.cy.js
  cypress/e2e/pages/access/platform-user-role.cy.js
  cypress/e2e/pages/base/header.cy.js
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/e2e/pages/cluster/online-offline-install.cy.js
  cypress/e2e/pages/cluster/registry.cy.js
  cypress/e2e/pages/cluster/template.cy.js
  cypress/e2e/pages/node/node.cy.js
  cypress/e2e/pages/region/region.cy.js
  cypress/support/commands.js
  cypress/support/resource.js
  src/locales/en.json
  src/locales/zh.json
Labels: size/XXL, dco-signoff: yes, do-not-merge/release-note-label-needed

#373 fix: can not add plugin repeat by unique
  src/pages/cluster/components/plugin/AddPlugin.jsx
Labels: size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#375 fix: delete backup space
  src/pages/cluster/containers/BackupPoint/actions/Delete.jsx
Labels: size/S, dco-signoff: yes, do-not-merge/release-note-label-needed

#377 fix: the storageclass form used by select or input
  src/components/FormRender/index.jsx
  src/components/FormRender/widgets/SelectInput/index.jsx
  src/pages/cluster/components/plugin/uiSchemas.js
Labels: size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed
