Repository kubeclipper/console, pull requests merged in 2023-03, with the labels that each got.

#378 perf: split e2e case
  cypress.config.js
  cypress/config/config-cluster.yaml
  cypress/config/config-others.yaml
  cypress/config/config.yaml
  cypress/plugins/index.js
Labels: approved, size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#379 fix: fix e2e case & set default language to en
  cypress/config/config.yaml
  cypress/support/resource.js
Labels: approved, size/XS, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#380 feat: split e2e test in workflow
  .github/workflows/full-e2e-test.yml
  cypress/e2e/pages/cluster/template.cy.js
Labels: size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#381 feat: update merge-report file
  .github/workflows/full-e2e-test.yml
Labels: size/XS, dco-signoff: yes, do-not-merge/release-note-label-needed

#382 fix: set default language to en
  cypress/support/commands.js
Labels: size/XS, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#383 fix: i18n
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/e2e/pages/cluster/template.cy.js
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Cluster/actions/RemoveNodes.jsx
  src/pages/cluster/containers/Cluster/actions/index.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
Labels: size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#384 fix: set default language to zh
  config/common.js
  cypress/config/config.yaml
  cypress/e2e/pages/cluster/cluster.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/e2e/pages/cluster/template.cy.js
  cypress/support/commands.js
  cypress/support/form-commands.js
  cypress/support/table-commands.js
Labels: size/S, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#385 feat: use secret for node ip
  .github/workflows/full-e2e-test.yml
Labels: size/XS, dco-signoff: yes, do-not-merge/release-note-label-needed

#386 feat: split e2e test for backup
  .github/workflows/full-e2e-test.yml
Labels: size/M, dco-signoff: no, do-not-merge/release-note-label-needed

#388 feat: update e2e test in workflow
  .github/workflows/full-e2e-test.yml
  cypress/config/config-backup.yaml
  cypress/config/config-cluster.yaml
  cypress/config/config.yaml
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/support/commands.js
Labels: size/S, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#387 fix: add cypree login wait time
  config/common.js
  cypress/config/config-backup.yaml
  cypress/config/config-cluster.yaml
  cypress/config/config-others.yaml
  cypress/config/kubeconfig.yaml
  cypress/e2e/pages/cluster/backup.cy.js
  cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  cypress/e2e/pages/cluster/template.cy.js
  cypress/support/commands.js
  cypress/support/form-commands.js
  cypress/support/resource.js
Labels: size/M, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed

#389 feat: use secret for docs node in e2e workflow
  .github/workflows/full-e2e-test.yml
  cypress/config/config-backup.yaml
  cypress/config/config-cluster.yaml
  cypress/config/config-online.yaml
Labels: size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#390 fix: modify backup waiting time
  cypress/e2e/pages/cluster/backup.cy.js
Labels: size/XS, dco-signoff: yes, do-not-merge/release-note-label-needed

#391 fix: fix git no tag build err
  config/webpack.e2e.js
  config/webpack.prod.js
Labels: approved, size/XS, dco-signoff: yes, do-not-merge/release-note-label-needed

#392 fix: remove workflow e2e
  .github/workflows/full-e2e-test.yml
Labels: size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#393 fix: remove workflow e2e
  .github/workflows/full-e2e-test.yml
Labels: size/M, dco-signoff: yes, do-not-merge/release-note-label-needed

#394 feat: add external domain&domainPort for create cluster
  src/components/FormItem/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Cluster/actions/Edit.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
  src/utils/validate.js
Labels: kind/feature, approved, size/L, lgtm, dco-signoff: yes, do-not-merge/release-note-label-needed

#396 feat: add external domain&domainPort for create cluster (#394)
  src/components/FormItem/index.jsx
  src/locales/en.json
  src/locales/zh.json
  src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Cluster/actions/Edit.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
  src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
  src/utils/validate.js
Labels: kind/feature, size/L, dco-signoff: yes, do-not-merge/release-note-label-needed

#397 fix: fix externaldomain for create cluster
  src/pages/cluster/containers/Cluster/actions/Create/index.jsx
  src/pages/cluster/containers/Cluster/actions/Edit.jsx
Labels: size/XS, kind/bug, dco-signoff: yes, do-not-merge/release-note-label-needed
